

//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"
#include "SplitPage.xaml.h"




void ::YouTube::SplitPage::InitializeComponent()
{
    if (_contentLoaded)
        return;

    _contentLoaded = true;

    // Call LoadComponent on ms-appx:///SplitPage.xaml
    ::Windows::UI::Xaml::Application::LoadComponent(this, ref new ::Windows::Foundation::Uri(L"ms-appx:///SplitPage.xaml"), ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);

    // Get the CollectionViewSource named 'itemsViewSource'
    itemsViewSource = safe_cast<::Windows::UI::Xaml::Data::CollectionViewSource^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"itemsViewSource"));
    // Get the ColumnDefinition named 'primaryColumn'
    primaryColumn = safe_cast<::Windows::UI::Xaml::Controls::ColumnDefinition^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"primaryColumn"));
    // Get the ColumnDefinition named 'secondaryColumn'
    secondaryColumn = safe_cast<::Windows::UI::Xaml::Controls::ColumnDefinition^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"secondaryColumn"));
    // Get the Grid named 'titlePanel'
    titlePanel = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"titlePanel"));
    // Get the ListView named 'itemListView'
    itemListView = safe_cast<::Windows::UI::Xaml::Controls::ListView^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"itemListView"));
    // Get the ScrollViewer named 'itemDetail'
    itemDetail = safe_cast<::Windows::UI::Xaml::Controls::ScrollViewer^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"itemDetail"));
    // Get the Grid named 'itemDetailGrid'
    itemDetailGrid = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"itemDetailGrid"));
    // Get the StackPanel named 'itemDetailTitlePanel'
    itemDetailTitlePanel = safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"itemDetailTitlePanel"));
    // Get the TextBlock named 'itemTitle'
    itemTitle = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"itemTitle"));
    // Get the TextBlock named 'itemSubtitle'
    itemSubtitle = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"itemSubtitle"));
    // Get the AppBarButton named 'backButton'
    backButton = safe_cast<::Windows::UI::Xaml::Controls::AppBarButton^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"backButton"));
    // Get the TextBlock named 'pageTitle'
    pageTitle = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"pageTitle"));
    // Get the VisualStateGroup named 'ViewStates'
    ViewStates = safe_cast<::Windows::UI::Xaml::VisualStateGroup^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"ViewStates"));
    // Get the VisualState named 'PrimaryView'
    PrimaryView = safe_cast<::Windows::UI::Xaml::VisualState^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"PrimaryView"));
    // Get the VisualState named 'SinglePane'
    SinglePane = safe_cast<::Windows::UI::Xaml::VisualState^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"SinglePane"));
    // Get the VisualState named 'SinglePane_Detail'
    SinglePane_Detail = safe_cast<::Windows::UI::Xaml::VisualState^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"SinglePane_Detail"));
}

void ::YouTube::SplitPage::Connect(int connectionId, Platform::Object^ target)
{
    switch (connectionId)
    {
    case 1:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::Selector^>(target))->SelectionChanged +=
            ref new ::Windows::UI::Xaml::Controls::SelectionChangedEventHandler(this, (void (::YouTube::SplitPage::*)(Platform::Object^, Windows::UI::Xaml::Controls::SelectionChangedEventArgs^))&SplitPage::ItemListView_SelectionChanged);
        break;
    }
    (void)connectionId; // Unused parameter
    (void)target; // Unused parameter
    _contentLoaded = true;
}

