

#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Data {
                ref class CollectionViewSource;
            }
        }
    }
}
namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class ColumnDefinition;
                ref class Grid;
                ref class ListView;
                ref class ScrollViewer;
                ref class StackPanel;
                ref class TextBlock;
                ref class AppBarButton;
            }
        }
    }
}
namespace Windows {
    namespace UI {
        namespace Xaml {
            ref class VisualStateGroup;
            ref class VisualState;
        }
    }
}

namespace YouTube
{
    partial ref class SplitPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Data::CollectionViewSource^ itemsViewSource;
        private: ::Windows::UI::Xaml::Controls::ColumnDefinition^ primaryColumn;
        private: ::Windows::UI::Xaml::Controls::ColumnDefinition^ secondaryColumn;
        private: ::Windows::UI::Xaml::Controls::Grid^ titlePanel;
        private: ::Windows::UI::Xaml::Controls::ListView^ itemListView;
        private: ::Windows::UI::Xaml::Controls::ScrollViewer^ itemDetail;
        private: ::Windows::UI::Xaml::Controls::Grid^ itemDetailGrid;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ itemDetailTitlePanel;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ itemTitle;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ itemSubtitle;
        private: ::Windows::UI::Xaml::Controls::AppBarButton^ backButton;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ pageTitle;
        private: ::Windows::UI::Xaml::VisualStateGroup^ ViewStates;
        private: ::Windows::UI::Xaml::VisualState^ PrimaryView;
        private: ::Windows::UI::Xaml::VisualState^ SinglePane;
        private: ::Windows::UI::Xaml::VisualState^ SinglePane_Detail;
    };
}

